### ISSUE TITLE
Leaflet double-click zoom blurs label text

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#10]
This one's very odd. If you zoom in Leaflet with a double-click, the label text blurs. Using the + zoom control does not blur it. No idea why.

**Comment by tomchadwin** [comment]
Update: does not always blur. Is something being positioned on a fraction of a pixel, resulting in antialiasing?

**Comment by JamesLMilner** [comment]
I'll investigate and get back to you. Potentially a Leaflet issue itself.

**Comment by JamesLMilner** [comment]
I can't replicate this. Which browser are you using? I've tested in Chrome and Firefox. Can you post a screenshot of what you're seeing?

**Comment by tomchadwin** [comment]
Chrome/Win7x64

I'll try Firefox tomorrow, and also see if I can replicate outside Labelgun.

**Comment by tomchadwin** [comment]
Before:
![before](https://cloud.githubusercontent.com/assets/7840213/21883990/72e829a2-d8a9-11e6-92b7-cf81f8681ac2.png)

After:
![after](https://cloud.githubusercontent.com/assets/7840213/21883995/779571ee-d8a9-11e6-8156-ff0bbfc56a46.png)

**Comment by tomchadwin** [comment]
Also experienced in Chrome/Mac and Firefox/Mac.

Can't recreate in Firefox/Win, Chrome/Xenial, Firefox/Xenial.

**Comment by JamesLMilner** [comment]
Hmm...strange. I'll pass it around the engineering team at work and see if they can reproduce also.

**Comment by JamesLMilner** [comment]
Is this still causing a problem @tomchadwin ?

**Comment by tomchadwin** [comment]
Oo, no. On an initial quick test (Chrome/Win), all seems well. Nice one. Will close.
