### ISSUE TITLE
Add /dist directory with compiled file

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#11]
In other words, place `https://unpkg.com/labelgun@0.1.1/lib/labelgun.min.js` in a `/dist` directory. Updating it can probably be automated with eg Paver or some such tool.

**Comment by tomchadwin** [comment]
> it can probably be automated with eg Paver

Or perhaps with your existing webpack job.

**Comment by JamesLMilner** [comment]
Hi @tomchadwin I think what you're looking for is in the lib directory. Might be worth changing the lib folder to dist? I'll have a think

**Comment by tomchadwin** [comment]
*blush*. Er, yeah. That.

I guess minified could go in`/dist`, and leave unminified in `/lib`.
