### ISSUE TITLE
Leaflet example doesn't use L.Tooltip?

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#12]
Warning: slightly rambling ignorant thought follows.

Obviously, Labelgun is mapping-library-agnostic, which is great. It also aims to be extremely efficient, using rbush under the hood. This is also splendid.

However, the Leaflet example doesn't (I think) use Leaflet 1's new `L.Tooltip`. Is it possible to use it? There would be obvious advantages to using it. It could be that failing to use it compromises performance (a guess).

**Comment by JamesLMilner** [comment]
I think it does under the hood since we're using Leaflet 1's builtin functions: 

https://github.com/Geovation/labelgun/blob/master/examples/leaflet/example.js#L25

The tooltip plugin was merged into Leaflet as far as im aware.

**Comment by tomchadwin** [comment]
Ah, apologies. I missed it. Great.
