### ISSUE TITLE
Add GH pages so examples work online

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#13]

**Comment by JamesLMilner** [comment]
Working on this! Might mean you have to change your PR to go back to the CDN though rather than relative files

**Comment by tomchadwin** [comment]
Wouldn't be a problem, though I don't quite see why it would be necessary.

**Comment by JamesLMilner** [comment]
The way we publish gh-pages is using subtrees which mean you can't access parent level folders. The benefit is that it makes deploying changes to examples to gh-pages **much** easier.

The GH Page is now live by the way: https://geovation.github.io/labelgun/

**Comment by tomchadwin** [comment]
But it does work:

https://geovation.github.io/labelgun/leaflet/index.html

Or do you mean you've not implemented subtrees yet?

**Comment by tomchadwin** [comment]
Closing for now - will revert examples to CDN if they fail in the future.

**Comment by JamesLMilner** [comment]
Yes it works currently because they're using the CDN currently. If you use the local library they will fail because it can't access code outside the subtree.

**Comment by tomchadwin** [comment]
OK. I was out of sync. Think my PR is good to go now.
