### ISSUE TITLE
Works with all geometries?

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#14]
Probably a silly question, but does this work with lines and polygons?

**Comment by JamesLMilner** [comment]
Anything that you can provide a bounding box for! For polygons some libraries have a getBoundingBox function or similar, lines probably a little more work as you'd have to write the function yourself and would require some maths.

**Comment by tomchadwin** [comment]
OK. I suspect to increase usage of this, it would be worth coding such examples.
