### ISSUE TITLE
Confusing Documentation

### ISSUE THREAD

**Issue by tonu42** [Geovation/labelgun#19]
I feel like this may be under utilized because of how confusing setting it up is. 

Also when using browser only getting errors that prevent running.

**Comment by JamesLMilner** [comment]
Hi there @tonu42. Thanks for raising an issue about this. Could you be a little more explicit about what you have trouble with? There are examples for both Leaflet and OpenLayers if you are using those libraries. 

Regarding errors; can you please show me the code and the resulting error messages you are getting? It's quite hard to advise/help without that information.

**Comment by JamesLMilner** [comment]
I have now added auto generated JSDoc which hopefully should help :) 

Check it out here, along with the Leaflet and OpenLayers 4 demos: 

https://geovation.github.io/labelgun/

**Comment by JamesLMilner** [comment]
As there's been no follow up on this I am going to close it. If you have more specific feedback feel free to open a new issue.
