### ISSUE TITLE
Performance enhancements

### ISSUE THREAD

**Issue by JamesLMilner** [Geovation/labelgun#20]
It would be great to improve the performance of the library. You can use : 

```npm run benchmark``` 

to check the general speed of the update function (probably the most crucial for most people).

**Comment by ibesora** [comment]
See pull request #30

**Comment by JamesLMilner** [comment]
Great work @ibesora! Some nice little boosts there. For all intents and purposes I think this should be fast enough for all major use cases. If people feel they need to shave off any more milliseconds then we can look into reopening with specific concerns.
