### ISSUE TITLE
Multiple layers

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#22]
I think there's a simple enhancement to make this work across multiple layers. PR coming to see whether you think it works.

**Comment by tomchadwin** [comment]
In fact this only needs to be implemented in the example, not the lib.

**Comment by JamesLMilner** [comment]
Hey Tom just going to close this, if people are confused regarding multiple layers they can see this issue and your PR and see how it gets done. I just want to keep the example as simple as possible for now.

**Comment by tomchadwin** [comment]
+1. When initially doing this, I hadn't fully separated the lib from the integration in my head.
