### ISSUE TITLE
Differentiate initial hide() from subsequent hide()

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#24]
I've added an opacity transition to the style, and this works well. However, this means all overlapping labels initially display on map load, immediately transitioning to fade out.

What would be the easiest way to differentiate calls to `hideLabel()` made initially from subsequent ones? The transition could then be removed for the subsequent calls.

**Comment by JamesLMilner** [comment]
Hey @tomchadwin , one way to fix this could you set the initial labels to hidden?

**Comment by tomchadwin** [comment]
Yes, that would of course be more sensible. However, I didn't think the Leaflet example explicitly did display them. I'll look through my code and see if I can tweak it. Thanks.

**Comment by tomchadwin** [comment]
Closing this for now, as the requirement was based on a misapplication of the lib.
