### ISSUE TITLE
Issues with new algorithm

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#26]
I'm not sure the new algorithm is as successful as the old. I'm getting frequent overlaps:

![2017-09-06 13_10_12-index html](https://user-images.githubusercontent.com/7840213/30111269-eeb64cf6-9304-11e7-905e-c1360acd44ab.png)

I would also say that some plausible candidates for labelling have no label:

![2017-09-06 13_12_28-index html](https://user-images.githubusercontent.com/7840213/30111339-2616b370-9305-11e7-8270-7803118d070f.png)

**Comment by JamesLMilner** [comment]
can you confirm the version you're using? All unit tests are passing and all examples seem okay on 5.0.1:

https://geovation.github.io/labelgun/examples/leaflet/index.html

**Comment by tomchadwin** [comment]
Master: https://github.com/Geovation/labelgun/blob/master/lib/labelgun.js

**Comment by JamesLMilner** [comment]
Mmm, strange. Can you link me the code?

**Comment by tomchadwin** [comment]
I'll upload a zip. It's got a lot of cruft, as it's generated from QGIS. I don't think the cruft's to blame, though...

**Comment by tomchadwin** [comment]
[q2w_lg.zip](https://github.com/Geovation/labelgun/files/1281085/q2w_lg.zip)

Zooming in and then back out again gives me the overlap.

**Comment by JamesLMilner** [comment]
@tomchadwin I examined your code, looks like you're using zoomstart, you want to be using zoomend (as this is the location of the labels at rest). I tried it and it worked as expected :) Also I updated the version to 6.0.0, making some minor changes to the API, the one that would effect you is destroy() becomes reset().

**Comment by tomchadwin** [comment]
Ah, I see! A daft mistake, with hindsight. I was trying to:

- sync the fade transition nicely
- leave `zoomend` free because I already use it for scale-dependent layer visibility

I'll change back to `zoomend`. Sorry for the noise.

**Comment by tomchadwin** [comment]
Just to confirm - all working. It also now works in QtWebkit, so your latest work means it's transpiling perfectly too, as far as I can tell. Thanks so much!
