### ISSUE TITLE
Examples without node

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#4]
I'm not a node user, but the examples require it.

**Comment by JamesLMilner** [comment]
Hey Tom, thanks for your interest.

Let me have a think about this one. In honesty my gut reaction is to keep it the way it is as node is a very common dependency for most web development projects these days. Having said that maybe it'd be nicer to see if there's CDNs that could be used instead.

**Comment by tomchadwin** [comment]
It's just how I go about integrating it with a Python QGIS plugin which is very much not targeted at web devs.

**Comment by devonbarrett** [comment]
Adding the project to NPM (#6) will allow easy integration with the http://www.jsdelivr.com/ CDN

**Comment by JamesLMilner** [comment]
I've add to NPM now so when that gets picked up by jsdelivr I'll see if there's a nice way to swap out all the dependencies to CDNs

**Comment by JamesLMilner** [comment]
This should now be possible! We have published to NPM which published to unpkg : 

https://unpkg.com/labelgun@0.1.1/lib/labelgun.js

@tomchadwin want to confirm that you can see these examples now? I'll close the issue after.

**Comment by tomchadwin** [comment]
Nice! I'll check it out and let you know. Thanks very much indeed!

**Comment by tomchadwin** [comment]
It fails, but for a different reason. Probably worth a new issue and closing this one off, though I'm not able to confirm all else works.

**Comment by tomchadwin** [comment]
New Leaflet example works perfectly (if #8 is merged). Thank you!
