### ISSUE TITLE
Example fails locally

### ISSUE THREAD

**Issue by tomchadwin** [Geovation/labelgun#7]
```
example.js:20 Fetch API cannot load file:///C:/Users/tchadwin/Desktop/labelgun-master/examples/geojson/cupcakes.geojson. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ example.js:20
```

**Comment by tomchadwin** [comment]
Could either just inline the GeoJSON or use JSONP.

**Comment by JamesLMilner** [comment]
Seems sensible to me! Fetch isn't widely supported either so makes sense I think

**Comment by JamesLMilner** [comment]
Merged! @tomchadwin if all's okay we can close this issue :)

**Comment by tomchadwin** [comment]
Spiffing! Don't close yet - still working on the OpenLayers example.

**Comment by tomchadwin** [comment]
If you are happy to merge #9, this can definitely be closed.
